version: "3.8"

services:
  postgresql:
    image: postgres:18.0-alpine
    container_name: local_pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=local-db
#      - PGDATA=/var/lib/postgresql/data/pgdata
#    volumes:
#      - pg_data_lansus_volume:/var/lib/postgresql/data/pgdata

#volumes:
#  pg_data_lansus_volume:
